### ISSUE TITLE
Sudoswap

### ISSUE THREAD

**Issue by kenlly2018** [dappradar/nft-sales-adapters#185]
@[API key](https://dappradar.github.io/nft-sales-adapters/#/general/index?id=api-key)
Apply for API key by filling out form https://forms.gle/5E8hsZhyd94X9a3M7.

API keys are necessary to simplify testing of the adapters and even if we will review untested adapters, process will be a lot faster if developers tests adapters using API key before submitting a pull request.

Each API key has a limit of 5000 requests. If you need higher limit - [contact us](https://dappradar.github.io/nft-sales-adapters/#/contact-us).

[Supported protocols](https://dappradar.github.io/nft-sales-adapters/#/general/index?id=supported-protocols)
Ethereum
BNB Chain (Binance Smart Chain)
Polygon (Matic)
Avalanche
Tezos
[Environment configuration](https://dappradar.github.io/nft-sales-adapters/#/general/index?id=environment-configuration)
Create a copy of environment configuration

cp .env.dist .env
Fill DAPPRADAR_API_KEY with your [API key](https://dappradar.github.io/nft-sales-adapters/#/general/index?id=api-key).

**Comment by MarkZa007** [comment]
Good
