### ISSUE TITLE
NFTKey

### ISSUE THREAD

**Issue by lagrangedot** [dappradar/nft-sales-adapters#36]
_Website_ 
https://nftkey.app/

_Contracts (For guidance only)_
https://snowtrace.io/address/0x1A7d6ed890b6C284271AD27E7AbE8Fb5211D0739

_Blockchain_
Avalanche

_Type_
Marketplace

**Comment by jokullj** [comment]
Already added see: https://github.com/dappradar/nft-sales-adapters/pull/18
