### ISSUE TITLE
Integrate SudoSwap NFT Marketplace

### ISSUE THREAD

**Issue by dragosdydy** [dappradar/nft-sales-adapters#89]
There is a bounty on this issue on [Layer3](https://beta.layer3.xyz/bounties/integrate-sudoswap-nft-marketplace-to-dappradar). You can claim the bounty by completing this integration and by having the PR successfully approved by our team. The PR needs to have the "**sudoswap**" label to be eligible for the reward.

Please read more details about claiming the bounty on [Layer3](https://beta.layer3.xyz/communities/dappradar).

1. Read the repository docs and get yourself an API key - https://dappradar.github.io/nft-sales-adapters/#/general/index
2. Make sure you have your GitHub attached to your Layer3 account
3. Get familiar with SudoSwap - https://docs.sudoswap.xyz/
4. Build the integration and test it
5. Create a PR with the label "sudoswap"
6. Wait for the team to review and offer feedback
7. As soon as the PR is merged, you can claim your bounty on L3

_Tips about the integration: There might be a challenge with SudoSwap because you will need to parse the details from the parameters of function instead of the event._ [Etherscan tx example](https://etherscan.io/tx/0xb1a351f67b522f3d92cfaafc489ff1b4fcedcab418340d3504ee0813fd23541f)

**Comment by 0xRobin** [comment]
There's extra complexity here because you will also need to parse and aggregate raw eth trace data to determine the correct trade value.

**Comment by Mohammad7129** [comment]
#developers in Discord

**Comment by Mohammad7129** [comment]
#developers in Discord

**Comment by ehsantabli** [comment]
#developers in Discord

**Comment by rijulraj456** [comment]
#91

**Comment by rijulraj456** [comment]
#developers in Discord

**Comment by Hamed1992199** [comment]
#developers in Discord

**Comment by xingcuiping** [comment]
It's complicated, try to do it

**Comment by hull198710** [comment]
#developers in Discord

**Comment by xingcuiping** [comment]
The process of completion is learning

**Comment by hull198710** [comment]
#sudoswap  #developers in Discord "sudoswap"

**Comment by Shrona5665** [comment]
#developers in Discord

**Comment by bruce-tt** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by kanatoPapa** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by tuantran21022** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by zhoujiu2339** [comment]
这个任务怎么完成有指南吗

**Comment by wilson-hu88** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by ekoyanu99** [comment]
#developers in Discord

**Comment by Zagi-Zagi** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by serton952** [comment]
[#developers in Discord](https://dappradar.com/discord)

**Comment by serton952** [comment]
#developers in Discord

**Comment by Darth9000** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by MasoudMsd** [comment]
#developers in Discord

**Comment by Avdonin74** [comment]
> There is a bounty on this issue on [Layer3](https://beta.layer3.xyz/bounties/integrate-sudoswap-nft-marketplace-to-dappradar). You can claim the bounty by completing this integration and by having the PR successfully approved by our team. The PR needs to have the "**sudoswap**" label to be eligible for the reward.
> 
> Please read more details about claiming the bounty on [Layer3](https://beta.layer3.xyz/communities/dappradar).
> 
> 1. Read the repository docs and get yourself an API key - https://dappradar.github.io/nft-sales-adapters/#/general/index
> 2. Make sure you have your GitHub attached to your Layer3 account
> 3. Get familiar with SudoSwap - https://docs.sudoswap.xyz/
> 4. Build the integration and test it
> 5. Create a PR with the label "sudoswap"
> 6. Wait for the team to review and offer feedback
> 7. As soon as the PR is merged, you can claim your bounty on L3
> 
> _Tips about the integration: There might be a challenge with SudoSwap because you will need to parse the details from the parameters of function instead of the event._ [Etherscan tx example](https://etherscan.io/tx/0xb1a351f67b522f3d92cfaafc489ff1b4fcedcab418340d3504ee0813fd23541f)

**Comment by MasoudMsd** [comment]
sudoswap #developers in Discord

**Comment by Roozbehjabari** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by cryptolady332** [comment]
sudoswap great app for NFT!

**Comment by cryptolady332** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by liboheng** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by www5674** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by Tsubasalayer3** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by marirok** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by ProVodaG** [comment]
sudoswap good project
#sudoswap #developers in Discord "sudoswap"

**Comment by crypto-death** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by ProVodaG** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by crypto-death** [comment]
"sudoswap".  ?

**Comment by atsushi0612** [comment]
#sudoswap #developers in Discord "sudoswap"

**Comment by kamrankarami400** [comment]
> 

#sudoswap #developer in Discord "sudoswap".....
